#ifndef QTHANDLEBARSJS_GLOBAL_H
#define QTHANDLEBARSJS_GLOBAL_H

#include <QtCore/QtGlobal>

#ifdef QTHANDLEBARSJS_STATIC
#   define QTHANDLEBARSJSSHARED_EXPORT
#else
#   ifdef QTHANDLEBARSJS_LIBRARY
#       define QTHANDLEBARSJS_SHARED_EXPORT Q_DECL_EXPORT
#   else
#       define QTHANDLEBARSJS_SHARED_EXPORT Q_DECL_IMPORT
#   endif
#endif

#endif // QTHANDLEBARSJS_GLOBAL_H
